variables:
  # Name of your Azure DevOps service connection to your AML workspace
  ml_workspace_connection: 'ml_workspace_connection'

  # Name of your AML workspace and its resource group
  ml_workspace_name: 'mlops-demo'
  ml_workspace_rg: 'jonasro_amllabs'

  # Name of your Compute Cluster (needs to exist)
  ml_compute_name: 'cpu-cluster-demo'

  # Name of your experiment for training tracking
  ml_experiment_name: 'german-credit-experiment'

  # Model name for registration and its path in the repo
  ml_model_name: 'german-credit-basic-model'
  ml_model_path: 'models/german-credit-basic'

  # Desired model output name
  ml_model_filename: 'credit-prediction.pkl'

  # AKS cluster to deploy to (needs to exist)
  ml_aks_cluster: 'aks-inference'

  # Model deployment name
  ml_deployment_name: 'german-credit-deployment'